### ISSUE TITLE
Upgrade to a stable scheduler

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-engine#227]
Tokio 0.2 is out (https://tokio.rs/blog/2019-11-tokio-0-2/). We should upgrade to the stable version asap. It should have much faster scheduler and this is a nice thing to benchmark.

Until we can do so, we must wait for

- [x] tokio-postgres to upgrade (https://github.com/sfackler/rust-postgres/issues/519)
- [x] mysql_async to upgrade (https://github.com/blackbeam/mysql_async/issues/86)
- [x] hyper to upgrade (https://github.com/hyperium/hyper/issues/2025)
- [x] mobc to upgrade (https://github.com/importcjj/mobc/issues/7)

Then we start by:

- [x] Updating Quaint
- [x] Updating Query/Migration/Introspection Engines

**Comment by pimeys** [comment]
Done and done.
