### ISSUE TITLE
EPIC: new Introspection Engine

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engine#32]
The introspection connector for SQL is the component that introspects a SQL database and returns a Prisma schema. This gets implemented by our Freelancer Arve. 

Work packages are:
- [x] build the command driven by Unit Tests based on the idea to simply invert the behavior of the `DatabaseSchemaCalculator` in the migration engine.
- [x] build a binary that takes a Prisma connection url and introspects the database. The result is printed to stdout. This allows to try out the introspection internally.
- [x] add a JSON RPC API to the introspection engine
- [x] create integration tests to test complex schemas in an end to end fashion. Foundation for those tests can either be our collection of database schema examples or the tests in the typescript version of this command.

**Comment by timsuchanek** [comment]
We need the following commands/rpcs from the introspection engine, which are right now exposed by our TypeScript package `prisma-db-introspection`:
1. `introspect` - passing in a connection string, getting back a datamodel
2. `listSchemas` - when having Postgres, we need to be able to list the schemas for a database. Optimally in mysql we could also list the databases, when the rights allow it, it's optional though, as we can work around that in the init flow, where we use it as of now.
3. `getDatabaseMetadata` - Returns `sizeInBytes` and `countOfTables` of a concrete database (or schema in Postgres)

**Comment by mavilein** [comment]
The RPC API for the `introspection-engine` is implemented now. The names of the RPCs are `introspect`, `listDatabases` and `getDatabaseMetadata`. All rpcs take exactly one parameter. Here is an example of one RPC:
```
{"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"url":"file:/.../prisma/dev.db"}]}
```

Please note that the `params` are wrapped in array here. I tried out a new approach to define rpcs which is more ergonomic for us but requires this array.

**Comment by divyenduz** [comment]
Internal note: dropping, waiting for @do4gr to be back 🙌
